<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Links macros -->

<!-- invisible joint center for separating DH transformation and physical components -->
<xacro:macro name="DH" params="name">
<link name="${name}">
  <!-- - ->
  <visual>
    <geometry>
      <cylinder radius="0.030" length="0.100"/>
    </geometry>
    <material name="black"/>
  </visual>
  <!- - -->
</link>
</xacro:macro>


<!-- schunk PRL model joint -->
<xacro:macro name="PRL" params="name type">
<link name="${name}" >
    <visual>
        <geometry>
            <cylinder radius="${0.001*type/2}" length="${0.0013*type}"/>
        </geometry>
        <material name="golden"/>
    </visual>
    
    <collision>
        <geometry>
            <cylinder radius="${0.001*type/1.2}" length="0.118"/>
        </geometry>
    </collision>
</link>
</xacro:macro>


<!-- general connector with definable shape -->
TODO: remove macro? or disable collision in another way
<xacro:macro name="Connector" params="name *shape">
<link name="${name}">
  <visual>
    <origin xyz="0 0 0.030"/>
    <geometry>
      <xacro:insert_block name="shape" />
    </geometry>
    <material name="black"/>
  </visual>

<!--
  <collision>
    <geometry>
      <xacro:insert_block name="shape" />
    </geometry>
  </collision>
-->
</link>
</xacro:macro>

<!-- long flat connector between joints -->
<xacro:macro name="Connector_long" params="name length">
<link name="${name}" >
    <visual>
        <origin xyz="${0.001*length/2} 0 ${0.061}"/>
        <geometry>
            <box size="${0.001*length+0.07} 0.105 0.038"/>
        </geometry>
        <material name="black"/>
    </visual>
    
    <collision>
        <origin xyz="${0.001*length/2} 0 ${0.060+0.05}"/>
        <geometry>
            <box size="${0.001*length+0.07+0.04} 0.110 0.08"/>
        </geometry>
    </collision>
</link>
</xacro:macro>

<xacro:macro name="GripperFinger" params="name reflect">
<link name="${name}" >
    <visual>
    <!--<origin xyz="${0.047+0.035} 0 ${reflect*(gripper_space+0.010)/2}"/>-->
        <origin xyz="${0.035} 0 ${1*0.020/2}"/> <!--offsets to set fingers ontop the gripper and beside the coordinate center-->
        <geometry>
            <box size="0.070 0.030 0.020"/> <!--real finger size-->
        </geometry>
        <material name="aluminium"/>
    </visual>
    
</link>
</xacro:macro>

</robot>
